require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JobordersController do

  # This should return the minimal set of attributes required to create a valid
  # Joborder. As you add validations to Joborder, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JobordersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all joborders as @joborders" do
      joborder = Joborder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:joborders).should eq([joborder])
    end
  end

  describe "GET show" do
    it "assigns the requested joborder as @joborder" do
      joborder = Joborder.create! valid_attributes
      get :show, {:id => joborder.to_param}, valid_session
      assigns(:joborder).should eq(joborder)
    end
  end

  describe "GET new" do
    it "assigns a new joborder as @joborder" do
      get :new, {}, valid_session
      assigns(:joborder).should be_a_new(Joborder)
    end
  end

  describe "GET edit" do
    it "assigns the requested joborder as @joborder" do
      joborder = Joborder.create! valid_attributes
      get :edit, {:id => joborder.to_param}, valid_session
      assigns(:joborder).should eq(joborder)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Joborder" do
        expect {
          post :create, {:joborder => valid_attributes}, valid_session
        }.to change(Joborder, :count).by(1)
      end

      it "assigns a newly created joborder as @joborder" do
        post :create, {:joborder => valid_attributes}, valid_session
        assigns(:joborder).should be_a(Joborder)
        assigns(:joborder).should be_persisted
      end

      it "redirects to the created joborder" do
        post :create, {:joborder => valid_attributes}, valid_session
        response.should redirect_to(Joborder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved joborder as @joborder" do
        # Trigger the behavior that occurs when invalid params are submitted
        Joborder.any_instance.stub(:save).and_return(false)
        post :create, {:joborder => {}}, valid_session
        assigns(:joborder).should be_a_new(Joborder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Joborder.any_instance.stub(:save).and_return(false)
        post :create, {:joborder => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested joborder" do
        joborder = Joborder.create! valid_attributes
        # Assuming there are no other joborders in the database, this
        # specifies that the Joborder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Joborder.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => joborder.to_param, :joborder => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested joborder as @joborder" do
        joborder = Joborder.create! valid_attributes
        put :update, {:id => joborder.to_param, :joborder => valid_attributes}, valid_session
        assigns(:joborder).should eq(joborder)
      end

      it "redirects to the joborder" do
        joborder = Joborder.create! valid_attributes
        put :update, {:id => joborder.to_param, :joborder => valid_attributes}, valid_session
        response.should redirect_to(joborder)
      end
    end

    describe "with invalid params" do
      it "assigns the joborder as @joborder" do
        joborder = Joborder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Joborder.any_instance.stub(:save).and_return(false)
        put :update, {:id => joborder.to_param, :joborder => {}}, valid_session
        assigns(:joborder).should eq(joborder)
      end

      it "re-renders the 'edit' template" do
        joborder = Joborder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Joborder.any_instance.stub(:save).and_return(false)
        put :update, {:id => joborder.to_param, :joborder => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested joborder" do
      joborder = Joborder.create! valid_attributes
      expect {
        delete :destroy, {:id => joborder.to_param}, valid_session
      }.to change(Joborder, :count).by(-1)
    end

    it "redirects to the joborders list" do
      joborder = Joborder.create! valid_attributes
      delete :destroy, {:id => joborder.to_param}, valid_session
      response.should redirect_to(joborders_url)
    end
  end

end
